install:
  - bundle update
env:
  - RAILS_VERSION=4.0.0
  - RAILS_VERSION=4.1.0
  - RAILS_VERSION=4.2.0
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx
  - jruby
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
